# Generated by Django 5.2.5 on 2025-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_registration_phone_alter_registration_srn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketconfirmation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='ticketconfirmation',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticketconfirmation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
