# Generated by Django 5.2.5 on 2025-08-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_ticketconfirmation_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketconfirmation',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='ticketconfirmation',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticketconfirmation',
            name='verified',
        ),
    ]
